'use strict';
const labels=['大象上船並畫線','大象上岸','裝石子至標記線','稱石子的總重量'];
const descriptions=['大象站在船上，官員沿水面在船身畫線','大象已上岸，空船浮起','石子裝在船上，船下沉至標記線','官員用秤稱石子'];
const state={pictures:[],words:[],selected:null,drag:null,checked:false};
function shuffled(){let result;do{result=[0,1,2,3];for(let i=3;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}}while(result.some((id,i)=>id===i));return result;}
function status(text,kind=''){const el=document.getElementById('feedback');el.textContent=text;el.className='feedback '+kind;}
function render(){for(const type of ['pictures','words']){const root=document.getElementById(type);root.replaceChildren();state[type].forEach((id,index)=>{const slot=document.createElement('div');slot.className='slot';const heading=document.createElement('div');heading.className='position';heading.textContent=`第${['一','二','三','四'][index]}步`;slot.append(heading);const card=document.createElement('button');card.type='button';card.draggable=true;card.className='card '+(type==='words'?'word':'');card.dataset.index=index;card.dataset.kind=type;card.setAttribute('aria-pressed',String(state.selected?.type===type&&state.selected.index===index));card.setAttribute('aria-label',`${type==='pictures'?'步驟圖':'動作字詞'}，位置${index+1}，${type==='pictures'?descriptions[id]:labels[id]}`);if(type==='pictures'){const p=document.createElement('div');p.className='picture';p.dataset.id=id;p.setAttribute('aria-hidden','true');p.innerHTML='<span class="number-mask">圖</span>';card.append(p);const caption=document.createElement('div');caption.className='picture-caption';caption.innerHTML='<span>點選交換／拖動</span><span class="grip" aria-hidden="true">⠿</span>';card.append(caption);}else{card.textContent=labels[id];const grip=document.createElement('span');grip.className='grip';grip.setAttribute('aria-hidden','true');grip.textContent='⠿';card.append(grip);}if(state.selected?.type===type&&state.selected.index===index)card.classList.add('selected');if(state.checked)card.classList.add(id===index?'correct':'incorrect');card.onclick=()=>select(type,index);card.onkeydown=e=>{const delta=['ArrowLeft','ArrowUp'].includes(e.key)?-1:['ArrowRight','ArrowDown'].includes(e.key)?1:0;if(delta){e.preventDefault();const to=index+delta;if(to>=0&&to<4){swap(type,index,to);document.querySelector(`#${type} [data-index="${to}"]`).focus();}}else if(e.key==='Escape'){state.selected=null;render();document.querySelector(`#${type} [data-index="${index}"]`).focus();}};card.ondragstart=e=>{state.drag={type,index};state.selected=null;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',type+':'+index);};card.ondragover=e=>{if(state.drag?.type===type){e.preventDefault();e.dataTransfer.dropEffect='move';card.classList.add('drag-over');}};card.ondragleave=()=>card.classList.remove('drag-over');card.ondrop=e=>{e.preventDefault();if(state.drag?.type===type)swap(type,state.drag.index,index);state.drag=null;card.classList.remove('drag-over');};card.ondragend=()=>{state.drag=null;document.querySelectorAll('.drag-over').forEach(c=>c.classList.remove('drag-over'));};slot.append(card);root.append(slot);});}}
function select(type,index){if(state.selected?.type===type){const from=state.selected.index;if(from===index){state.selected=null;render();status('已取消選取。');}else swap(type,from,index);}else{state.selected={type,index};render();status(`已選取${type==='pictures'?'圖片':'字詞'}，再點同一排的另一張卡片。`);}document.querySelector(`#${type} [data-index="${index}"]`).focus();}
function swap(type,from,to){if(from===to)return;[state[type][from],state[type][to]]=[state[type][to],state[type][from]];state.selected=null;state.checked=false;render();status('已交換位置。兩排都排好後，按「檢查答案」。');}
function reset(){state.pictures=shuffled();do{state.words=shuffled();}while(state.words.every((id,i)=>id===state.pictures[i]));state.selected=null;state.drag=null;state.checked=false;render();status('兩排都已打亂，開始排序吧！');}
document.getElementById('check').onclick=()=>{state.selected=null;state.checked=true;render();const p=state.pictures.filter((id,i)=>id===i).length;const w=state.words.filter((id,i)=>id===i).length;if(p===4&&w===4)status('全部排對了！你已掌握曹沖稱象的四個步驟。','success');else status(`圖片 ${p}/4 正確・字詞 ${w}/4 正確。橙色邊框的卡片再想一想！`,'retry');};
document.getElementById('reset').onclick=reset;
const fs=document.getElementById('fullscreen');if(!document.fullscreenEnabled)fs.hidden=true;fs.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{status('這個瀏覽器未能進入全螢幕；仍可照常遊戲。');}};document.addEventListener('fullscreenchange',()=>{fs.textContent=document.fullscreenElement?'退出全螢幕 ↙':'全螢幕 ↗';});
reset();
